# Generated by Django 4.1.4 on 2022-12-23 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_withdrawalrequest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositconfirmation',
            name='investor_user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_confirmation', to=settings.AUTH_USER_MODEL),
        ),
    ]
