# Generated by Django 4.1.4 on 2022-12-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_depositconfirmation_investor_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='slug',
        ),
    ]
